trigger:
- task: Maven@4
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  mavenOptions: '-Xmx3072m'
  mavenPomFile: 'pom.xml'
  javaVersion: '11'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenBuild
    displayName: Maven Build Job
    steps:
    - task: Maven@3
      displayName: 'Maven Build'
      inputs:
        mavenPomFile: '$(mavenPomFile)'
        goals: 'clean package'
        options: '$(mavenOptions)'
        mavenOptions: '-Dmaven.java.version=$(JavaVersion)'
        jdkVersionOption: '$(javaVersion)'